apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: order-cheeseburger
  title: Order Cheeseburger
  description: Create an order for cheeseburger with customizable size, sauces, and toppings.
spec:
  owner: kitchen
  type: service
  parameters:
    - title: Cheeseburger Order Configuration
      required:
        - size
      properties:
        size:
          type: string
          title: Size
          enum:
            - small
            - medium
            - large
          description: Choose the cheeseburger size.
        sauces:
          type: array
          title: Sauces
          items:
            type: string
          description: Choose your favorite sauces for the cheeseburger.
          enum:
            - ketchup
            - mustard
            - mayonnaise
          enumNames:
            - Ketchup
            - Mustard
            - Mayonnaise
        extras:
          type: array
          title: Toppings/Extras
          description: Additional toppings or extras for the cheeseburger.
          items:
            type: string
          enum:
            - lettuce
            - tomato
            - bacon
            - cheese
          enumNames:
            - Lettuce
            - Tomato
            - Bacon
            - Cheese
  steps:
    - id: create-git-repo
      name: Create Git Repository
      action: git:createRepository
      input:
        repoName: cheeseburger-order-${{ parameters.size }}
        repoDescription: 'Cheeseburger order with size, sauces, and extras'
        repoVisibility: private
        owner: '{{owner}}'
    - id: write-order-file
      name: Write Order File
      action: file:write
      input:
        targetPath: 'order.txt'
        content: |
          Cheeseburger Size: ${{ parameters.size }}
          Sauces: ${{ parameters.sauces }}
          Extras: ${{ parameters.extras }}
    - id: commit-order-file
      name: Commit and Push Order File
      action: git:commitAndPush
      input:
        repoRef: ${{ steps['create-git-repo'].output.repoRef }}
        files:
          - order.txt
        commitMessage: 'Initial commit for cheeseburger order'
  output:
    links:
      - url: '${{ steps["create-git-repo"].output.repositoryUrl }}'
        title: 'Git Repository for Cheeseburger Order'