apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: order-cheeseburger
  title: Order Cheeseburger
  description: Create an order for cheeseburger with customizable size, sauces, and toppings.
spec:
  owner: kitchen-team
  type: main
  parameters:
    - title: Cheeseburger Order Configuration
      required:
        - size
      properties:
        size:
          type: string
          title: Size
          enum:
            - small
            - medium
            - large
          description: Choose the cheeseburger size.
        sauces:
          type: array
          title: Sauces
          description: Choose your favorite sauces for the cheeseburger.
          items:
            type: string
            enum:
              - ketchup
              - mustard
              - mayonnaise
            enumNames:
              - Ketchup
              - Mustard
              - Mayonnaise
          uniqueItems: true
          ui:widget: checkboxes 
        extras:
          type: array
          title: Toppings/Extras
          description: Additional toppings or extras for the cheeseburger.
          items:
            type: string
            enum:
              - lettuce
              - tomato
              - bacon
              - cheese
            enumNames:
              - Lettuce
              - Tomato
              - Bacon
              - Cheese
          uniqueItems: true
          ui:widget: checkboxes
  steps:
    - id: submit-order
      name: Submit Order
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/log-forwarding'
        headers:
          Content-Type: 'application/json'
        body:
          event:
            action: submit-order
            attributes:
              menu-item: cheeseburger
              size: ${{ parameters.size }}
              sauces: ${{ parameters.sauces }}
              extras: ${{ parameters.extras }}

  output:
    orderResponse: '{{ steps["submit-order"].output.body }}'
    orderStatusCode: '{{ steps["submit-order"].output.code }}'
    orderHeaders: '{{ steps["submit-order"].output.headers }}'