apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: order-double-cheeseburger
  title: Order Double Cheeseburger
  description: Create an order for double cheeseburger with customizable size, sauces, and toppings.
spec:
  owner: kitchen-team
  type: main
  parameters:
    - title: Double Cheeseburger Order Configuration
      required:
        - size
      properties:
        size:
          type: string
          title: Size
          description: Choose the size of the double cheeseburger.
          enum:
            - medium
            - large
        sauces:
          type: array
          title: Sauces
          description: Choose sauces for the double cheeseburger.
          items:
            type: string
            enum:
              - ketchup
              - mayonnaise
              - mustard
            enumNames:
              - Ketchup
              - Mayonnaise
              - Mustard
          uniqueItems: true
          ui:widget: checkboxes
        toppings:
          type: array
          title: Toppings
          description: Choose toppings for the double cheeseburger.
          items:
            type: string
            enum:
              - lettuce
              - tomato
              - onion
              - bacon
            enumNames:
              - Lettuce
              - Tomato
              - Onion
              - Bacon
          uniqueItems: true
          ui:widget: checkboxes
  steps:
    - id: submit-order
      name: Submit Order
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/log-forwarding'
        headers:
          content-type: 'application/json'
        body:
          event:
            action: submit-order
            attributes:
              menu-item: doublecheeseburger
              size: ${{ parameters.size }}
              sauces: ${{ parameters.sauces }}
              extras: ${{ parameters.toppings }}

  output:
    orderResponse: '{{ steps["submit-order"].output.body }}'
    orderStatusCode: '{{ steps["submit-order"].output.code }}'
    orderHeaders: '{{ steps["submit-order"].output.headers }}'