apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: order-fries
  title: Order Fries
  description: Create an order for fries with customizable size and sauces.
spec:
  owner: kitchen-team
  type: side
  parameters:
    - title: Fries Order Configuration
      required:
        - size
      properties:
        size:
          type: string
          title: Size
          enum:
            - small
            - medium
            - large
          description: Choose the size of the fries.
        sauces:
          type: array
          title: Sauces
          description: Choose your favorite sauces for the fries.
          items:
            type: string 
            enum:
              - ketchup
              - mayonnaise
              - barbecue
            enumNames:
              - Ketchup
              - Mayonnaise
              - Barbecue
          uniqueItems: true
          ui:widget: checkboxes        
  steps:
    - id: submit-order
      name: Submit Order
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/log-forwarding'
        headers:
          content-type: 'application/json'
        body:
          event:
            action: submit-order
            attributes:
              menu-item: fries
              size: ${{ parameters.size }}
              sauces: ${{ parameters.sauces }}

  output:
    orderResponse: '{{ steps["submit-order"].output.body }}'
    orderStatusCode: '{{ steps["submit-order"].output.code }}'
    orderHeaders: '{{ steps["submit-order"].output.headers }}'