apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: order-iced-tea
  title: Order Iced Tea
  description: Create an order for iced tea with customizable flavor, size, and additional options.
spec:
  owner: customer-service-team
  type: drink
  parameters:
    - title: Iced Tea Order Configuration
      required:
        - flavor
        - size
      properties:
        flavor:
          type: string
          title: Flavor
          description: Choose the iced tea flavor.
          enum:
            - lemon
            - peach
            - raspberry
            - plain
          enumNames:
            - Lemon
            - Peach
            - Raspberry
            - Plain
        size:
          type: string
          title: Size
          description: Select the iced tea size.
          enum:
            - small
            - medium
            - large
        ice:
          type: boolean
          title: Add Ice
          description: Whether to include ice.
          default: true
        sweetened:
          type: boolean
          title: Sweetened
          description: Whether the iced tea is sweetened.
          default: false
  steps:
    - id: submit-order
      name: Submit Order
      action: http:backstage:request
      input:
        method: 'POST'
        path: '/proxy/log-forwarding'
        headers:
          content-type: 'application/json'
        body:
          event:
            action: submit-order
            attributes:
              menu-item: icedtea
              size: ${{ parameters.size }}
              flavor: ${{ parameters.flavor }}
              ice: ${{ parameters.ice }}
              sweetened: ${{ parameters.sweetened }}             

  output:
    orderResponse: '{{ steps["submit-order"].output.body }}'
    orderStatusCode: '{{ steps["submit-order"].output.code }}'
    orderHeaders: '{{ steps["submit-order"].output.headers }}'