apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-ai-demo
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: backstage-ai-demo
    targetRevision: 0.1.0
    repoURL: 'https://github.com/pfeifferj/backstage-ai-demo'
    helm:
      releaseName: backstage-ai-demo
      valueFiles:
        - values.yaml
      
  syncPolicy:
    automated:
      selfHeal: true
