apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-ai-demo
  namespace: openshift-gitops
spec:
  destination:
    namespace: backstage-ai-demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    chart: backstage-ai-demo
    targetRevision: 0.1.0
    repoURL: 'https://pfeifferj.github.io/backstage-ai-demo/'
    helm:
      releaseName: backstage-ai-demo
      valueFiles:
        - charts/vackstage-ai-demo/values.yaml 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true