---
name: Build and Push Images

on:
  push:
    paths:
      - 'log-forwarding/**'
      - 'zombie/**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['log-forwarding', 'zombie']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Podman
        uses: redhat-actions/setup-podman@v1

      - name: Read namespace from Helm values
        id: helm_values
        run: |
          NAMESPACE=$(yq e '.namespace' ${{ matrix.dir }}/helm/values.yaml)
          echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
          echo "::set-output name=namespace::$NAMESPACE"

      - name: Build image
        run: |
          cd ${{ matrix.dir }}
          podman build -t default-route-openshift-image-registry.apps.ocp4-prd.josie.cloud/${{ steps.helm_values.outputs.namespace }}/${{ matrix.dir }}:latest .

      - name: Log in to OpenShift registry
        run: podman login default-route-openshift-image-registry.apps.ocp4-prd.josie.cloud -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push image
        run: podman push default-route-openshift-image-registry.apps.ocp4-prd.josie.cloud/${{ steps.helm_values.outputs.namespace }}/${{ matrix.dir }}:latest

      - name: Print image url
        run: echo "Image pushed to default-route-openshift-image-registry.apps.ocp4-prd.josie.cloud/${{ steps.helm_values.outputs.namespace }}/${{ matrix.dir }}:latest"
