---
name: Build and Push Zombie & Log-Forwarding

on:
  # push:
    # paths:
      # - 'images/log-forwarding/**'
      # - 'images/zombie/**'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['log-forwarding', 'zombie']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read namespace & cluster url from Helm values
        id: helm_values
        run: |
          REGISTRY=$(yq e '.registry_org_url' helm/values.yaml)
          echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV
      
      - name: Log in to registry
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ env.REGISTRY }}
 
      - name: Build image using Buildah
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          context: images/${{ matrix.dir }}
          containerfiles: images/${{ matrix.dir }}/Containerfile
          image: ${{ matrix.dir }}
          tags: latest
          tls-verify: true

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.REGISTRY }}

      - name: Print image url
        run: echo "Image pushed to ${{ env.REGISTRY }}/${{ matrix.dir }}:latest"
