name: Publish Helm
on: 
  workflow_dispatch:
jobs: 
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.0.1

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore.
          changed=$(ct --config ./ct.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$charts"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ./ct.yaml 

      - name: Run docs-testing (helm-docs)
        uses: buttahtoast/helm-release-action@master
        with:
          charts: "${{ steps.list-changed.outputs.changed_charts }}"
        if: steps.list-changed.outputs.changed == 'true'  
 
      - name: Run kube-linter 
        uses: buttahtoast/helm-release-action@master
        with:
          exec: "linter"
          charts: "${{ steps.list-changed.outputs.changed_charts }}"
        if: steps.list-changed.outputs.changed == 'true'  

      - name: Run Unit-Tests
        uses: buttahtoast/helm-release-action@master
        with:
          exec: "unit-tests"
          charts: "${{ steps.list-changed.outputs.changed_charts }}"
        if: steps.list-changed.outputs.changed == 'true'

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"